config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles
  get "signup", to: "users#new"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 5, maximum: 20}
  validates :description, presence: true, length: {minimum: 10, maximum: 30}
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence:true, length: {minimum:3, maximum:25}
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :articles, dependent: :destroy
  validates :username, presence: true,
            uniqueness: {case_sensitive: false}, length:{ minimum: 3, maximum: 25 }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true,
            uniqueness: {case_sensitive: false}, length: {maximum:105},
            format: {with: VALID_EMAIL_REGEX}
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  def show

  end
  def index
    @articles = Article.all
  end
  def new
    @article = Article.new
  end
  def edit

  end
  def create
    @article = Article.new(article_params)
    @article.user = current_user 
    if @article.save
      flash[:notice] = "Article was added successfully!"
      redirect_to @article
    else
      render "new"
    end
  end
  def update
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated!"
      redirect_to @article
    else
      render 'edit'
    end
  end
  def destroy
      @article.destroy
      redirect_to articles_path
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end
  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def hello
  end
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      # redirect_to user
      redirect_to root_path
    else
      flash.now[:alert] = "Invalid login credentials"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out successfully!"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def show
    @articles = @user.articles
  end

  def index
    @users = User.all
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha blog #{@user.username}, successfully signed up"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    flash[:notice]="User successfully and all associated articles deleted!"
    redirect_to articles_path
  end
  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User updated successfully!"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !!current_user
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan = "3">Actions</th>
      <th>Author</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article|%>
    <tr class="flex gap-x-5">
      <td>
        <%=article.title%>
      </td>
      <td>
        <%=article.description%>
      </td>
      <td>
        <%=link_to 'Show', article_path(article) %>
      </td>
      <% if logged_in? && article.user == current_user %>
        <td>
          <%=link_to 'Edit', edit_article_path(article) %>
        </td>
        <td>
          <%=link_to 'Delete', article_path(article), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    } %>
        </td>
        <%end%>
        <td class="px-4 text-xl font-mono text-orange-500"><%=article.user.username if article.user%></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h1>The following errors occured!</h1>
  <ul>
    <%@article.errors.full_messages.each do |e|%>
      <li><%=e%></li>
      <%end%>
  </ul>
<%end%>
<%= form_with(model: @article,  local: true, data: { turbo: false })  do |f|%>
  <p>
    <%= f.label :title%><br/>
    <%= f.text_field :title%>
  </p>
  <p>
    <%= f.label :description%><br/>
    <%= f.text_area :description%>
  </p>
  <p>
    <%=f.submit%>
  </p>
<%end%>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
  <%= render "form"%>
<p>
  <%= link_to 'Cancel and return back to articles', articles_path %>
</p>

app/views/articles/index.html.erb
<h1>Listing articles page</h1>
<%= render 'article'%>
<p>
  <%= link_to "Create new article", new_article_path %>
</p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>
  <%= render "form" %>
<p >
  <%= link_to "Back to articles", articles_path %>
</p>

app/views/articles/show.html.erb
<h1>Showing articles Details</h1>
<p>Title: <%= @article.title %></p>
<p>Description: <%= @article.description %> </p>
<p class="text-blue-500 text-2xl">By <%=@article.user.username%></p>
  <%if logged_in? && @article.user == current_user%>
    <p>
      <%= link_to 'Edit article', edit_article_path(@article) %>
    </p>
    <p>
      <%= link_to 'Delete article', article_path(@article), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                      }%>
    </p>
  <%end%>
<p>
  <%= link_to 'Back to articles', articles_path %>
</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
  <%=msg%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Alpha Blog1" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/messages'%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="text-blue-500 text-2xl">This is our about us page!</h1>
<p>
  <%= link_to 'Our Articles', articles_path %> |
  <%= link_to 'Home page', root_path %>
</p>
<p>
  <%= link_to "Log out", logout_path, class: "text-blue-500", method: :delete %>
</p>

app/views/pages/home.html.erb
<h1 class="text-blue-500 text-2xl">Welcome to articles listing!</h1>
<p>
  <%= link_to 'Our Articles', articles_path, class: "text-blue-500" %> |
  <%= link_to 'About page', about_path, class: "text-blue-500" %>
</p>
<%=link_to 'Bloggers', users_path, class:"text-green-500" %>
<%if logged_in?%>
  <div>
    <p>
      <%= link_to "Logout", logout_path, class: "text-blue-500" %>
    </p>
    <p>
      <%= link_to current_user.username, current_user, class: "text-blue-500" %>
    </p>
    <p>
      <%= link_to "Delete User", user_path(current_user), class: "text-blue-500", data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                  } %>
    </p>
  </div>
<%else%>
  <div class="flex gap-x-10">
    <p>
    <%= link_to "Sign Up", signup_path, class: "text-blue-500" %>
    </p>
    <p>
      <%= link_to "Log in", login_path, class: "text-blue-500" %>
    </p>
  </div>
<%end%>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <h1>The following errors occured!</h1>
  <ul>
    <%@user.errors.full_messages.each do |e|%>
      <li><%=e%></li>
      <%end%>
  </ul>
<%end%>
<%= form_with(model: @user,  local: true, data: { turbo: false })  do |u|%>
  <p>
    <%= u.label :username%><br/>
    <%= u.text_field :username%>
  </p>
  <p>
    <%= u.label :email%><br/>
    <%= u.email_field :email%>
  </p>
  <p>
    <%= u.label :password%><br/>
    <%= u.password_field :password%>
  </p>
  <p>
    <%=u.submit(@user.new_record? ? "Sign up" : "Update account")%>
  </p>
<%end%>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>
  <%= render "form"%>
<p>
  <%= link_to 'Cancel and return back to articles', articles_path %>
</p>

app/views/users/index.html.erb
<h1>Alpha bloggers</h1>

<div>
  <div>
    <% @users.each do |user|%>
    <div class="mb-30">
      <div class="flex gap-x-5">
        <p>
          by <%=link_to user.username, user %>
        </p>
      </div>
      <div class="flex gap-x-5">
        <p>
          Number of articles: <%=link_to user.articles.count %>
        </p>
      </div>
      <div class="flex gap-x-10">
          <%=link_to 'View profile', user %> |
          <%=link_to 'Edit profile', edit_user_path(user) %>
      </div>
      <div>
        <p class="italic">Joined at <%=user.created_at%></p>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up for Alpha blog</h1>
  <%= render "form" %>
<p >
  <%= link_to "Back to users", articles_path %>
</p>

app/views/users/show.html.erb
<h1><%=@user.username%>'s profile</h1>
<h2>Articles</h2>
<%= render 'articles/article'%>
<p>
  <%= link_to 'Cancel and return back to articles', articles_path %>
</p>
<p>
  <%= link_to "Log out", logout_path, class: "text-blue-500", data: {turbo_method: :delete } %>
</p>